export const SITE_NAME = "JK Electricals Vapi";
export const SITE_DOMAIN = "jkelectricalsvapi.in";
export const SITE_URL = `https://${SITE_DOMAIN}`;
export const SITE_DESCRIPTION =
  "JK Electricals is a Vapi-based industrial electrical, electronics and automation supplier for switchgear, PLC, VFD, HMI, SCADA, sensors, process controllers, contactors, relays, limit switches, flameproof products, industrial plugs and sockets, cable trays, cables, motors, lighting, panel accessories and distribution products from Siemens, Schneider Electric, ABB, Delta, Omron, Polycab, KEI and Legrand. Serving Vapi GIDC, Silvassa, Daman, Sarigam, Valsad and South Gujarat.";
export const SITE_TITLE = "JK Electricals Vapi | Industrial Electrical & Automation Supplier in Gujarat";
export const SITE_KEYWORDS = [
  "JK Electricals Vapi",
  "JK Electricals",
  "J K Electricals Vapi",
  "JK Electricals Gujarat",
  "electrical supplier Vapi",
  "electronics supplier Vapi",
  "electrical electronics supplier Vapi",
  "industrial electrical supplier Vapi",
  "industrial electronics supplier Vapi",
  "industrial automation supplier Vapi",
  "electrical dealer Vapi",
  "electronics dealer Vapi",
  "electronics seller Vapi",
  "electrical shop Vapi GIDC",
  "electrical material supplier Vapi",
  "electrical goods supplier Vapi",
  "electrical components supplier Vapi",
  "electronic components supplier Vapi",
  "industrial electrical distributor Vapi",
  "authorized electrical distributor Vapi",
  "PLC supplier Vapi",
  "VFD supplier Vapi",
  "HMI supplier Vapi",
  "SCADA supplier Vapi",
  "industrial sensor supplier Vapi",
  "proximity sensor supplier Vapi",
  "photoelectric sensor supplier Vapi",
  "fiber optic sensor supplier Vapi",
  "laser sensor supplier Vapi",
  "pressure sensor supplier Vapi",
  "RFID sensor supplier Vapi",
  "process controller supplier Vapi",
  "temperature controller supplier Vapi",
  "PID controller supplier Vapi",
  "digital timer supplier Vapi",
  "digital counter supplier Vapi",
  "Siemens dealer Vapi",
  "Siemens supplier Vapi",
  "Schneider dealer Vapi",
  "Schneider Electric supplier Vapi",
  "ABB dealer Vapi",
  "ABB supplier Vapi",
  "Delta VFD supplier Vapi",
  "Delta PLC dealer Vapi",
  "INVT dealer Vapi",
  "Omron sensor supplier Vapi",
  "Autonics supplier Vapi",
  "Pepperl Fuchs supplier Vapi",
  "Panasonic sensor supplier Vapi",
  "Mitsubishi PLC supplier Vapi",
  "Polycab cable dealer Vapi",
  "RR Kabel dealer Vapi",
  "KEI cable supplier Vapi",
  "Legrand dealer Vapi",
  "Lauritz Knudsen L&T supplier Vapi",
  "C&S Electric dealer Vapi",
  "Selec dealer Vapi",
  "Multispan dealer Vapi",
  "Secure meter dealer Vapi",
  "Elmex dealer Vapi",
  "Bharat Bijlee motor supplier Vapi",
  "switchgear supplier Gujarat",
  "switchgear dealer Vapi",
  "ACB supplier Vapi",
  "VCB supplier Vapi",
  "RCBO supplier Vapi",
  "isolator supplier Vapi",
  "changeover switch supplier Vapi",
  "MCCB supplier Vapi",
  "MCB supplier Vapi",
  "RCCB supplier Vapi",
  "DOL starter supplier Vapi",
  "contactor supplier Vapi",
  "relay supplier Vapi",
  "control relay supplier Vapi",
  "limit switch supplier Vapi",
  "flameproof products supplier Vapi",
  "flameproof electrical supplier Vapi",
  "industrial plugs sockets supplier Vapi",
  "industrial plug socket dealer Vapi",
  "cable tray supplier Vapi",
  "perforated cable tray supplier Vapi",
  "ladder cable tray supplier Vapi",
  "cable gland supplier Vapi",
  "terminal block supplier Vapi",
  "copper lug supplier Vapi",
  "aluminium lug supplier Vapi",
  "SMPS supplier Vapi",
  "industrial cables Vapi",
  "industrial cable supplier Gujarat",
  "HT cable supplier Vapi",
  "LT cable supplier Vapi",
  "instrumentation cable supplier Vapi",
  "solar cable supplier Vapi",
  "control cable supplier Vapi",
  "armoured cable supplier Vapi",
  "power cable supplier Vapi",
  "automation solutions Vapi",
  "authorized electrical dealer",
  "electrical stockist Vapi",
  "electrical wholesaler Vapi",
  "bulk electrical supplier Vapi",
  "OEM electrical supplier Vapi",
  "factory electrical supplier Vapi",
  "industrial lighting Gujarat",
  "industrial lighting supplier Vapi",
  "LED highbay supplier Vapi",
  "industrial flood light supplier Vapi",
  "explosion proof light supplier Vapi",
  "industrial fan supplier Vapi",
  "industrial motor supplier Vapi",
  "servo motor supplier Vapi",
  "gear motor supplier Vapi",
  "distribution board supplier Vapi",
  "panel accessories supplier Vapi",
  "control panel accessories Vapi",
  "Vapi GIDC electrical supplier",
  "electrical supplier Silvassa",
  "industrial electrical supplier Silvassa",
  "electrical supplier Daman",
  "industrial electrical supplier Daman",
  "electrical supplier Sarigam",
  "electrical supplier Umbergaon",
  "electrical supplier Pardi",
  "electrical supplier Valsad",
  "electrical supplier Navsari",
];
export const SITE_OG_IMAGE = `${SITE_URL}/og-image.svg`;
export const SITE_FAVICON = "/src/assets/logo.png";

export const SERVICE_AREAS = [
  "Vapi",
  "Vapi GIDC",
  "Silvassa",
  "Daman",
  "Sarigam",
  "Umbergaon",
  "Pardi",
  "Valsad",
  "Navsari",
  "Ankleshwar",
  "Bharuch",
  "Surat",
  "Dahej",
];

export const INDUSTRIES_SERVED = [
  "Chemical plants",
  "Pharmaceutical industry",
  "Food processing",
  "Packaging industry",
  "Plastic industry",
  "Textile industry",
  "Steel industry",
  "Power plants",
  "Water treatment plants",
  "Paper mills",
  "Machine builders",
  "OEM manufacturers",
  "Panel builders",
  "Infrastructure projects",
  "Commercial buildings",
  "Factories",
  "Warehouses",
  "Manufacturing plants",
  "Engineering companies",
  "Industrial contractors",
] as const;

export const COMMERCIAL_INTENTS = [
  "authorized dealer",
  "authorized distributor",
  "authorized supplier",
  "industrial supplier",
  "industrial electrical supplier",
  "electrical wholesaler",
  "electrical distributor",
  "electrical dealer",
  "electrical stockist",
  "automation supplier",
  "automation distributor",
  "automation dealer",
  "automation integrator",
  "control panel supplier",
  "OEM supplier",
  "factory supplier",
  "industrial equipment supplier",
  "bulk electrical supplier",
  "industrial electrical store",
  "industrial automation dealer",
  "industrial automation supplier",
] as const;

export const AI_SEARCH_TOPICS = [
  "industrial cables",
  "switchgear",
  "distribution boards",
  "process controllers",
  "electrical measurement",
  "industrial automation",
  "industrial sensors",
  "industrial lighting",
  "industrial fans",
  "motors",
  "heaters",
  "panel accessories",
  "flameproof products",
  "industrial plugs and sockets",
  "cable trays",
  "PLC",
  "VFD",
  "HMI",
  "SCADA",
  "MCB",
  "MCCB",
  "RCCB",
  "RCBO",
  "ACB",
  "VCB",
  "contactors",
  "relays",
  "limit switches",
  "proximity sensors",
  "photoelectric sensors",
  "thermocouples",
  "RTD sensors",
  "energy meters",
  "current transformers",
  "SMPS",
  "terminal blocks",
  "cable glands",
  "lugs and ferrules",
] as const;

export const ROUTES = [
  {
    path: "/",
    title: "Industrial Electrical & Automation Supplier in Vapi | JK Electricals",
    description:
      "JK Electricals is a Vapi-based industrial electrical, electronics and automation supplier for switchgear, PLC, VFD, sensors, process controllers, cables, motors, lighting, panel accessories, flameproof products, plugs, sockets and cable trays across South Gujarat.",
    priority: "1.0",
  },
  {
    path: "/about",
    title: "About JK Electricals Vapi | Industrial Distribution Experts",
    description:
      "Learn about JK Electricals, an authorized industrial electrical distributor in Vapi serving GIDC and nearby industrial hubs with genuine components and fast support.",
    priority: "0.8",
  },
  {
    path: "/products",
    title: "Industrial Electrical Products, Dealers & Automation Suppliers in Vapi | JK Electricals",
    description:
      "Find industrial electrical dealers, distributors, suppliers, stockists, and sellers for switchgear, cables, automation systems, sensors, motors, lighting, control panel components, and listed brands in Vapi.",
    priority: "0.9",
  },
  {
    path: "/brands",
    title: "Industrial Electrical Brands, Dealers & Suppliers in Vapi | JK Electricals",
    description:
      "Browse industrial electrical and automation brands supplied by JK Electricals Vapi, including Siemens, Schneider Electric, ABB, Delta, Omron, Polycab, KEI, Legrand, Autonics, and related category pages.",
    priority: "0.86",
  },
  {
    path: "/contact",
    title: "Contact JK Electricals Vapi | Industrial Supply Support",
    description:
      "Contact JK Electricals Vapi for industrial electrical products, quotations, bulk inquiries, and quick procurement support across Gujarat industrial hubs.",
    priority: "0.8",
  },
  {
    path: "/blog",
    title: "Industrial Electrical & Automation Blog | JK Electricals",
    description:
      "Read buying guides and topic resources for PLC, VFD, sensors, automation, switchgear, industrial safety, and maintenance procurement.",
    priority: "0.7",
  },
] as const;
